# Generated by Django 5.0.6 on 2024-06-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_vendor_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': 'Units'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': 'Vendors'},
        ),
    ]
