# Generated by Django 5.0.6 on 2024-06-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_customer_options_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='full_name',
            new_name='name',
        ),
    ]
