# Generated by Django 5.0.6 on 2024-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylanguage',
            name='language',
            field=models.CharField(choices=[], max_length=6),
        ),
        migrations.AlterField(
            model_name='productlanguage',
            name='language',
            field=models.CharField(choices=[], max_length=6),
        ),
    ]
