# Generated by Django 5.0.6 on 2024-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='language',
            field=models.CharField(blank=True, choices=[], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='settinglanguage',
            name='language',
            field=models.CharField(choices=[], max_length=6),
        ),
    ]
