# Generated by Django 5.0.6 on 2024-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='settinglang',
            name='lang',
        ),
        migrations.AddField(
            model_name='faq',
            name='language',
            field=models.CharField(blank=True, choices=[], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='settinglang',
            name='language',
            field=models.CharField(choices=[], default=1, max_length=6),
            preserve_default=False,
        ),
    ]
