# Generated by Django 5.0.6 on 2024-06-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_faq_lang_remove_settinglang_lang_faq_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('sp', 'Spanish')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='settinglang',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sp', 'Spanish')], max_length=6),
        ),
    ]
